# Default values for mystique.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
manifests:
  - name: mystique
    apiVersion: v1
    kind: Service
    annotations:
      marvel.mutant.name: mystique
    labels:
      xwoman: mystique
    spec:
      externalName: "{{ .Values.url }}"
      ports:
        - name: http
          port: 80
    body: {}

url: www.marvel.com
