{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubecon.serviceAccountName" . }}
  labels:
{{ include "kubecon.labels" . | indent 4 }}
{{- end -}}
